### ISSUE TITLE
Fold/Peel on Last Page Throws Error

### ISSUE THREAD

**Issue by Annodyne** [blasten/turn.js#112]
Currently using single mode (not that it matters) and I've manually set 'pages'.  On the last page, when I hover over corners 'tr' or 'br' I get:

folding is null (Line 2247)

After this error, functionality dies unless I reload or use the slider to change the page and reset things.

Clicking on one of these corners also generates an exception surely due to the fact that we can't proceed past the last page:

uncaught exception: TurnJsError: "10" is not a page for range

**Comment by blasten** [comment]
Are you using the 3rd release?

**Comment by Annodyne** [comment]
Currently on the 4th release.

**Comment by blasten** [comment]
I'll check that out

**Comment by blasten** [comment]
This problem was fixed in 4.0.7

**Comment by vadherdhaval** [comment]
This problem is still exist. I tried out with first basic example. just removed last page from the html and tried to flip but it throws me same error

**Comment by Annodyne** [comment]
It was fixed for me after updating files.

**Comment by blasten** [comment]
@vadherdhaval Can you share a snippet? You should only remove pages using the `removePage` method, because it takes care of the consistency of the book.
